import GLOBAL_CMS_NAME_TO_COMPONENT_MAP from './globalCmsNameToComponentMap';

const DYNAMIC_MODAL_UI_COMPONENTS_CMS_NAME_TO_COMPONENT_MAP = {
  ...GLOBAL_CMS_NAME_TO_COMPONENT_MAP
};

export default DYNAMIC_MODAL_UI_COMPONENTS_CMS_NAME_TO_COMPONENT_MAP;
